[package]
name = "crusty-midi-info"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
crustysynth = { path = "../crustysynth" }
