name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  static-checks:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt -v --check
      
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --no-deps --  --deny warnings
      


  rustdoc:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Generate docs
        run: cargo doc --no-deps -p crustysynth

      - name: Deploy docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc/crustysynth/

